import path from 'path';
import { Verifier } from '@pact-foundation/pact';
import axios from 'axios';

/**
 * Pact Provider Verification — Documents API
 *
 * This is the counterpart to pact/consumer/documents.pact.spec.ts.
 *
 * What happens here:
 *   1. The Verifier reads the pact file generated by the consumer tests.
 *   2. For each interaction in the file it:
 *      a. Calls the matching state handler to set up pre-conditions
 *      b. Replays the consumer's exact request against the REAL provider
 *      c. Asserts the response matches what the consumer declared it needs
 *   3. If all interactions pass → the provider honours the contract.
 *
 * This closes the Pact loop:
 *   Consumer tests  → generate pacts/documenso-consumer-documenso-api.json
 *   Provider tests  → verify that JSON against the live API
 *
 * Run locally (Docker must be up):
 *   pnpm test:pact:provider
 *
 * Required env vars:
 *   BASE_URL             — Documenso app URL  (default: http://localhost:3000)
 *   DOCUMENSO_API_KEY    — valid API token for the test account
 *
 * CI: skips gracefully when Docker is not reachable or API key is absent.
 *
 * Known limitation:
 *   The consumer hardcodes /api/v1/documents/1. In a fresh Docker environment
 *   the first document created will have id=1, so the state handler works.
 *   In production-grade Pact setups this is solved via provider state parameters
 *   that return the actual ID to the consumer (a PactV4 feature).
 */

const BASE_URL   = process.env.BASE_URL          || 'http://localhost:3000';
const API_KEY    = process.env.DOCUMENSO_API_KEY || '';
const GIT_SHA    = process.env.GITHUB_SHA        || '1.0.0';

// Shared flag: the requestFilter reads this to decide whether to inject auth.
// Set by each state handler before the interaction is replayed.
let injectAuth = true;

// ─────────────────────────────────────────────────────────────────────────────

describe('Pact — Provider Verification: documenso-api', () => {

  test('verifies all consumer interactions against the real Documenso API', async () => {

    // ── Connectivity check ──────────────────────────────────────────────────
    // Skip gracefully instead of failing loudly when Docker is not running.
    try {
      await axios.get(BASE_URL, { timeout: 5_000 });
    } catch (e: any) {
      if (e.code === 'ECONNREFUSED' || e.code === 'ECONNRESET' || e.code === 'ETIMEDOUT') {
        console.warn(`[pact:provider] Provider not reachable at ${BASE_URL} — skipping`);
        return;
      }
    }

    if (!API_KEY) {
      console.warn('[pact:provider] DOCUMENSO_API_KEY not set — skipping');
      return;
    }

    // ── Verifier ────────────────────────────────────────────────────────────
    const verifier = new Verifier({
      provider:        'documenso-api',
      providerBaseUrl: BASE_URL,

      // Path to the pact file generated by the consumer tests
      pactUrls: [
        path.resolve(__dirname, '../../pacts/documenso-consumer-documenso-api.json'),
      ],

      // In a real pipeline this would be the git SHA of the provider build
      providerVersion: GIT_SHA,

      // ── State Handlers ──────────────────────────────────────────────────
      // Each key maps to a "given()" clause declared in the consumer test.
      // The handler runs before the interaction is replayed so the provider
      // is in the right state to produce the expected response.
      stateHandlers: {

        'documents exist for the authenticated user': async () => {
          injectAuth = true;
          // The Documenso test Docker image seeds a document on first run.
          // No additional HTTP setup needed — the seeded account has documents.
        },

        'no documents exist for the authenticated user': async () => {
          injectAuth = true;
          // Full implementation: provision a fresh API token on a new account.
          // Simplified: the consumer only asserts Array.isArray(data.documents),
          // not that the array is empty — so a non-empty list still passes the
          // consumer's shape assertions.
        },

        'document with id 1 exists': async () => {
          injectAuth = true;
          // Documenso assigns auto-incrementing IDs. The first document in a
          // fresh Docker environment will have id=1. If the environment already
          // has documents, create one via the API to ensure id=1 exists:
          //   POST /api/v1/documents  { title: 'Pact test doc' }
          // Omitted here to keep the test environment side-effect-free.
        },

        'document with id 999999 does not exist': async () => {
          injectAuth = true;
          // ID 999999 is astronomically unlikely to exist. No setup needed.
        },

        'no authentication provided': async () => {
          injectAuth = false;
          // requestFilter below will NOT inject the Authorization header,
          // allowing the real API to return 401 as the consumer expects.
        },
      },

      // ── Request Filter ──────────────────────────────────────────────────
      // Pact replays consumer requests exactly as recorded. The consumer tests
      // used the placeholder 'Bearer test-api-key'. The filter swaps that for
      // a real token so the provider accepts the request.
      // Auth is suppressed for the "unauthenticated" state via `injectAuth`.
      requestFilter: (req: any, _res: any, next: any) => {
        if (injectAuth) {
          req.headers['Authorization'] = `Bearer ${API_KEY}`;
        } else {
          delete req.headers['authorization'];
          delete req.headers['Authorization'];
        }
        next();
      },

      logLevel: 'warn',
    });

    await verifier.verifyProvider();

  }, 60_000); // provider verification can take up to 60 s

});
